title: jwazne
description: > # this means to ignore newlines until "baseurl:"
  Hows to on technical subjects such as Business Intelligence / Data Science / Web development.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jwazne.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Julien Wazné # add your name
#author-img: david-freeman.jpg # add your photo
author-img: julien-wazne.png
about-author: Open source BI specialist<br>Full-stack developer<br>CTO & Co-founder.<br><br>Always hungry to learn and share new things. # add description
#twitter: # add your Twitter handle
#facebook: # add your Facebook handle
#github: jwazne # add your Github handle
linkedin: julienwazne # add your Linkedin handle
email: jwazne@gmail.com # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
